const db = [
  {
    country_name_en: "Afghanistan",
    country_name_fr: "Afghanistan (l')",
    alpha2: "AF",
    alpha3: "AFG",
    number: "004",
  },
  {
    country_name_en: "Åland Islands",
    country_name_fr: "Åland(les Îles)",
    alpha2: "AX",
    alpha3: "ALA",
    number: "248",
  },
  {
    country_name_en: "Albania",
    country_name_fr: "Albanie (l')",
    alpha2: "AL",
    alpha3: "ALB",
    number: "008",
  },
  {
    country_name_en: "Algeria",
    country_name_fr: "Algérie (l')",
    alpha2: "DZ",
    alpha3: "DZA",
    number: "012",
  },
  {
    country_name_en: "American Samoa",
    country_name_fr: "Samoa américaines (les)",
    alpha2: "AS",
    alpha3: "ASM",
    number: "016",
  },
  {
    country_name_en: "Andorra",
    country_name_fr: "Andorre (l')",
    alpha2: "AD",
    alpha3: "AND",
    number: "020",
  },
  {
    country_name_en: "Angola",
    country_name_fr: "Angola (l')",
    alpha2: "AO",
    alpha3: "AGO",
    number: "024",
  },
  {
    country_name_en: "Anguilla",
    country_name_fr: "Anguilla",
    alpha2: "AI",
    alpha3: "AIA",
    number: "660",
  },
  {
    country_name_en: "Antarctica",
    country_name_fr: "Antarctique (l')",
    alpha2: "AQ",
    alpha3: "ATA",
    number: "010",
  },
  {
    country_name_en: "Antigua and Barbuda",
    country_name_fr: "Antigua-et-Barbuda",
    alpha2: "AG",
    alpha3: "ATG",
    number: "028",
  },
  {
    country_name_en: "Argentina",
    country_name_fr: "Argentine (l')",
    alpha2: "AR",
    alpha3: "ARG",
    number: "032",
  },
  {
    country_name_en: "Armenia",
    country_name_fr: "Arménie (l')",
    alpha2: "AM",
    alpha3: "ARM",
    number: "051",
  },
  {
    country_name_en: "Aruba",
    country_name_fr: "Aruba",
    alpha2: "AW",
    alpha3: "ABW",
    number: "533",
  },
  {
    country_name_en: "Australia",
    country_name_fr: "Australie (l')",
    alpha2: "AU",
    alpha3: "AUS",
    number: "036",
  },
  {
    country_name_en: "Austria",
    country_name_fr: "Autriche (l')",
    alpha2: "AT",
    alpha3: "AUT",
    number: "040",
  },
  {
    country_name_en: "Azerbaijan",
    country_name_fr: "Azerbaïdjan (l')",
    alpha2: "AZ",
    alpha3: "AZE",
    number: "031",
  },
  {
    country_name_en: "Bahamas (the)",
    country_name_fr: "Bahamas (les)",
    alpha2: "BS",
    alpha3: "BHS",
    number: "044",
  },
  {
    country_name_en: "Bahrain",
    country_name_fr: "Bahreïn",
    alpha2: "BH",
    alpha3: "BHR",
    number: "048",
  },
  {
    country_name_en: "Bangladesh",
    country_name_fr: "Bangladesh (le)",
    alpha2: "BD",
    alpha3: "BGD",
    number: "050",
  },
  {
    country_name_en: "Barbados",
    country_name_fr: "Barbade (la)",
    alpha2: "BB",
    alpha3: "BRB",
    number: "052",
  },
  {
    country_name_en: "Belarus",
    country_name_fr: "Bélarus (le)",
    alpha2: "BY",
    alpha3: "BLR",
    number: "112",
  },
  {
    country_name_en: "Belgium",
    country_name_fr: "Belgique (la)",
    alpha2: "BE",
    alpha3: "BEL",
    number: "056",
  },
  {
    country_name_en: "Belize",
    country_name_fr: "Belize (le)",
    alpha2: "BZ",
    alpha3: "BLZ",
    number: "084",
  },
  {
    country_name_en: "Benin",
    country_name_fr: "Bénin (le)",
    alpha2: "BJ",
    alpha3: "BEN",
    number: "204",
  },
  {
    country_name_en: "Bermuda",
    country_name_fr: "Bermudes (les)",
    alpha2: "BM",
    alpha3: "BMU",
    number: "060",
  },
  {
    country_name_en: "Bhutan",
    country_name_fr: "Bhoutan (le)",
    alpha2: "BT",
    alpha3: "BTN",
    number: "064",
  },
  {
    country_name_en: "Bolivia (Plurinational State of)",
    country_name_fr: "Bolivie (État plurinational de)",
    alpha2: "BO",
    alpha3: "BOL",
    number: "068",
  },
  {
    country_name_en: "Bonaire, Sint Eustatius and Saba",
    country_name_fr: "Bonaire, Saint-Eustache et Saba",
    alpha2: "BQ",
    alpha3: "BES",
    number: "535",
  },
  {
    country_name_en: "Bosnia and Herzegovina",
    country_name_fr: "Bosnie-Herzégovine (la)",
    alpha2: "BA",
    alpha3: "BIH",
    number: "070",
  },
  {
    country_name_en: "Botswana",
    country_name_fr: "Botswana (le)",
    alpha2: "BW",
    alpha3: "BWA",
    number: "072",
  },
  {
    country_name_en: "Bouvet Island",
    country_name_fr: "Bouvet (l'Île)",
    alpha2: "BV",
    alpha3: "BVT",
    number: "074",
  },
  {
    country_name_en: "Brazil",
    country_name_fr: "Brésil (le)",
    alpha2: "BR",
    alpha3: "BRA",
    number: "076",
  },
  {
    country_name_en: "British Indian Ocean Territory (the)",
    country_name_fr: "Indien (le Territoire britannique de l'océan)",
    alpha2: "IO",
    alpha3: "IOT",
    number: "086",
  },
  {
    country_name_en: "Brunei Darussalam",
    country_name_fr: "Brunéi Darussalam (le)",
    alpha2: "BN",
    alpha3: "BRN",
    number: "096",
  },
  {
    country_name_en: "Bulgaria",
    country_name_fr: "Bulgarie (la)",
    alpha2: "BG",
    alpha3: "BGR",
    number: "100",
  },
  {
    country_name_en: "Burkina Faso",
    country_name_fr: "Burkina Faso (le)",
    alpha2: "BF",
    alpha3: "BFA",
    number: "854",
  },
  {
    country_name_en: "Burundi",
    country_name_fr: "Burundi (le)",
    alpha2: "BI",
    alpha3: "BDI",
    number: "108",
  },
  {
    country_name_en: "Cabo Verde",
    country_name_fr: "Cabo Verde",
    alpha2: "CV",
    alpha3: "CPV",
    number: "132",
  },
  {
    country_name_en: "Cambodia",
    country_name_fr: "Cambodge (le)",
    alpha2: "KH",
    alpha3: "KHM",
    number: "116",
  },
  {
    country_name_en: "Cameroon",
    country_name_fr: "Cameroun (le)",
    alpha2: "CM",
    alpha3: "CMR",
    number: "120",
  },
  {
    country_name_en: "Canada",
    country_name_fr: "Canada (le)",
    alpha2: "CA",
    alpha3: "CAN",
    number: "124",
  },
  {
    country_name_en: "Cayman Islands (the)",
    country_name_fr: "Caïmans (les Îles)",
    alpha2: "KY",
    alpha3: "CYM",
    number: "136",
  },
  {
    country_name_en: "Central African Republic (the)",
    country_name_fr: "République centrafricaine (la)",
    alpha2: "CF",
    alpha3: "CAF",
    number: "140",
  },
  {
    country_name_en: "Chad",
    country_name_fr: "Tchad (le)",
    alpha2: "TD",
    alpha3: "TCD",
    number: "148",
  },
  {
    country_name_en: "Chile",
    country_name_fr: "Chili (le)",
    alpha2: "CL",
    alpha3: "CHL",
    number: "152",
  },
  {
    country_name_en: "China",
    country_name_fr: "Chine (la)",
    alpha2: "CN",
    alpha3: "CHN",
    number: "156",
  },
  {
    country_name_en: "Christmas Island",
    country_name_fr: "Christmas (l'Île)",
    alpha2: "CX",
    alpha3: "CXR",
    number: "162",
  },
  {
    country_name_en: "Cocos (Keeling) Islands (the)",
    country_name_fr: "Cocos (les Îles)/ Keeling (les Îles)",
    alpha2: "CC",
    alpha3: "CCK",
    number: "166",
  },
  {
    country_name_en: "Colombia",
    country_name_fr: "Colombie (la)",
    alpha2: "CO",
    alpha3: "COL",
    number: "170",
  },
  {
    country_name_en: "Comoros (the)",
    country_name_fr: "Comores (les)",
    alpha2: "KM",
    alpha3: "COM",
    number: "174",
  },
  {
    country_name_en: "Congo (the Democratic Republic of the)",
    country_name_fr: "Congo (la République démocratique du)",
    alpha2: "CD",
    alpha3: "COD",
    number: "180",
  },
  {
    country_name_en: "Congo (the)",
    country_name_fr: "Congo (le)",
    alpha2: "CG",
    alpha3: "COG",
    number: "178",
  },
  {
    country_name_en: "Cook Islands (the)",
    country_name_fr: "Cook (les Îles)",
    alpha2: "CK",
    alpha3: "COK",
    number: "184",
  },
  {
    country_name_en: "Costa Rica",
    country_name_fr: "Costa Rica (le)",
    alpha2: "CR",
    alpha3: "CRI",
    number: "188",
  },
  {
    country_name_en: "Côte d'Ivoire",
    country_name_fr: "Côte d'Ivoire (la)",
    alpha2: "CI",
    alpha3: "CIV",
    number: "384",
  },
  {
    country_name_en: "Croatia",
    country_name_fr: "Croatie (la)",
    alpha2: "HR",
    alpha3: "HRV",
    number: "191",
  },
  {
    country_name_en: "Cuba",
    country_name_fr: "Cuba",
    alpha2: "CU",
    alpha3: "CUB",
    number: "192",
  },
  {
    country_name_en: "Curaçao",
    country_name_fr: "Curaçao",
    alpha2: "CW",
    alpha3: "CUW",
    number: "531",
  },
  {
    country_name_en: "Cyprus",
    country_name_fr: "Chypre",
    alpha2: "CY",
    alpha3: "CYP",
    number: "196",
  },
  {
    country_name_en: "Czechia",
    country_name_fr: "Tchéquie (la)",
    alpha2: "CZ",
    alpha3: "CZE",
    number: "203",
  },
  {
    country_name_en: "Denmark",
    country_name_fr: "Danemark (le)",
    alpha2: "DK",
    alpha3: "DNK",
    number: "208",
  },
  {
    country_name_en: "Djibouti",
    country_name_fr: "Djibouti",
    alpha2: "DJ",
    alpha3: "DJI",
    number: "262",
  },
  {
    country_name_en: "Dominica",
    country_name_fr: "Dominique (la)",
    alpha2: "DM",
    alpha3: "DMA",
    number: "212",
  },
  {
    country_name_en: "Dominican Republic (the)",
    country_name_fr: "dominicaine (la République)",
    alpha2: "DO",
    alpha3: "DOM",
    number: "214",
  },
  {
    country_name_en: "Ecuador",
    country_name_fr: "Équateur (l')",
    alpha2: "EC",
    alpha3: "ECU",
    number: "218",
  },
  {
    country_name_en: "Egypt",
    country_name_fr: "Égypte (l')",
    alpha2: "EG",
    alpha3: "EGY",
    number: "818",
  },
  {
    country_name_en: "El Salvador",
    country_name_fr: "El Salvador",
    alpha2: "SV",
    alpha3: "SLV",
    number: "222",
  },
  {
    country_name_en: "Equatorial Guinea",
    country_name_fr: "Guinée équatoriale (la)",
    alpha2: "GQ",
    alpha3: "GNQ",
    number: "226",
  },
  {
    country_name_en: "Eritrea",
    country_name_fr: "Érythrée (l')",
    alpha2: "ER",
    alpha3: "ERI",
    number: "232",
  },
  {
    country_name_en: "Estonia",
    country_name_fr: "Estonie (l')",
    alpha2: "EE",
    alpha3: "EST",
    number: "233",
  },
  {
    country_name_en: "Eswatini",
    country_name_fr: "Eswatini (l')",
    alpha2: "SZ",
    alpha3: "SWZ",
    number: "748",
  },
  {
    country_name_en: "Ethiopia",
    country_name_fr: "Éthiopie (l')",
    alpha2: "ET",
    alpha3: "ETH",
    number: "231",
  },
  {
    country_name_en: "Falkland Islands (the) [Malvinas]",
    country_name_fr: "Falkland (les Îles)/Malouines (les Îles)",
    alpha2: "FK",
    alpha3: "FLK",
    number: "238",
  },
  {
    country_name_en: "Faroe Islands (the)",
    country_name_fr: "Féroé (les Îles)",
    alpha2: "FO",
    alpha3: "FRO",
    number: "234",
  },
  {
    country_name_en: "Fiji",
    country_name_fr: "Fidji (les)",
    alpha2: "FJ",
    alpha3: "FJI",
    number: "242",
  },
  {
    country_name_en: "Finland",
    country_name_fr: "Finlande (la)",
    alpha2: "FI",
    alpha3: "FIN",
    number: "246",
  },
  {
    country_name_en: "France",
    country_name_fr: "France (la)",
    alpha2: "FR",
    alpha3: "FRA",
    number: "250",
  },
  {
    country_name_en: "French Guiana",
    country_name_fr: "Guyane française (la )",
    alpha2: "GF",
    alpha3: "GUF",
    number: "254",
  },
  {
    country_name_en: "French Polynesia",
    country_name_fr: "Polynésie française (la)",
    alpha2: "PF",
    alpha3: "PYF",
    number: "258",
  },
  {
    country_name_en: "French Southern Territories (the)",
    country_name_fr: "Terres australes françaises (les)",
    alpha2: "TF",
    alpha3: "ATF",
    number: "260",
  },
  {
    country_name_en: "Gabon",
    country_name_fr: "Gabon (le)",
    alpha2: "GA",
    alpha3: "GAB",
    number: "266",
  },
  {
    country_name_en: "Gambia (the)",
    country_name_fr: "Gambie (la)",
    alpha2: "GM",
    alpha3: "GMB",
    number: "270",
  },
  {
    country_name_en: "Georgia",
    country_name_fr: "Géorgie (la)",
    alpha2: "GE",
    alpha3: "GEO",
    number: "268",
  },
  {
    country_name_en: "Germany",
    country_name_fr: "Allemagne (l')",
    alpha2: "DE",
    alpha3: "DEU",
    number: "276",
  },
  {
    country_name_en: "Ghana",
    country_name_fr: "Ghana (le)",
    alpha2: "GH",
    alpha3: "GHA",
    number: "288",
  },
  {
    country_name_en: "Gibraltar",
    country_name_fr: "Gibraltar",
    alpha2: "GI",
    alpha3: "GIB",
    number: "292",
  },
  {
    country_name_en: "Greece",
    country_name_fr: "Grèce (la)",
    alpha2: "GR",
    alpha3: "GRC",
    number: "300",
  },
  {
    country_name_en: "Greenland",
    country_name_fr: "Groenland (le)",
    alpha2: "GL",
    alpha3: "GRL",
    number: "304",
  },
  {
    country_name_en: "Grenada",
    country_name_fr: "Grenade (la)",
    alpha2: "GD",
    alpha3: "GRD",
    number: "308",
  },
  {
    country_name_en: "Guadeloupe",
    country_name_fr: "Guadeloupe (la)",
    alpha2: "GP",
    alpha3: "GLP",
    number: "312",
  },
  {
    country_name_en: "Guam",
    country_name_fr: "Guam",
    alpha2: "GU",
    alpha3: "GUM",
    number: "316",
  },
  {
    country_name_en: "Guatemala",
    country_name_fr: "Guatemala (le)",
    alpha2: "GT",
    alpha3: "GTM",
    number: "320",
  },
  {
    country_name_en: "Guernsey",
    country_name_fr: "Guernesey",
    alpha2: "GG",
    alpha3: "GGY",
    number: "831",
  },
  {
    country_name_en: "Guinea",
    country_name_fr: "Guinée (la)",
    alpha2: "GN",
    alpha3: "GIN",
    number: "324",
  },
  {
    country_name_en: "Guinea-Bissau",
    country_name_fr: "Guinée-Bissau (la)",
    alpha2: "GW",
    alpha3: "GNB",
    number: "624",
  },
  {
    country_name_en: "Guyana",
    country_name_fr: "Guyana (le)",
    alpha2: "GY",
    alpha3: "GUY",
    number: "328",
  },
  {
    country_name_en: "Haiti",
    country_name_fr: "Haïti",
    alpha2: "HT",
    alpha3: "HTI",
    number: "332",
  },
  {
    country_name_en: "Heard Island and McDonald Islands",
    country_name_fr: "Heard-et-Îles MacDonald (l'Île)",
    alpha2: "HM",
    alpha3: "HMD",
    number: "334",
  },
  {
    country_name_en: "Holy See (the)",
    country_name_fr: "Saint-Siège (le)",
    alpha2: "VA",
    alpha3: "VAT",
    number: "336",
  },
  {
    country_name_en: "Honduras",
    country_name_fr: "Honduras (le)",
    alpha2: "HN",
    alpha3: "HND",
    number: "340",
  },
  {
    country_name_en: "Hong Kong",
    country_name_fr: "Hong Kong",
    alpha2: "HK",
    alpha3: "HKG",
    number: "344",
  },
  {
    country_name_en: "Hungary",
    country_name_fr: "Hongrie (la)",
    alpha2: "HU",
    alpha3: "HUN",
    number: "348",
  },
  {
    country_name_en: "Iceland",
    country_name_fr: "Islande (l')",
    alpha2: "IS",
    alpha3: "ISL",
    number: "352",
  },
  {
    country_name_en: "India",
    country_name_fr: "Inde (l')",
    alpha2: "IN",
    alpha3: "IND",
    number: "356",
  },
  {
    country_name_en: "Indonesia",
    country_name_fr: "Indonésie (l')",
    alpha2: "ID",
    alpha3: "IDN",
    number: "360",
  },
  {
    country_name_en: "Iran (Islamic Republic of)",
    country_name_fr: "Iran (République Islamique d')",
    alpha2: "IR",
    alpha3: "IRN",
    number: "364",
  },
  {
    country_name_en: "Iraq",
    country_name_fr: "Iraq (l')",
    alpha2: "IQ",
    alpha3: "IRQ",
    number: "368",
  },
  {
    country_name_en: "Ireland",
    country_name_fr: "Irlande (l')",
    alpha2: "IE",
    alpha3: "IRL",
    number: "372",
  },
  {
    country_name_en: "Isle of Man",
    country_name_fr: "Île de Man",
    alpha2: "IM",
    alpha3: "IMN",
    number: "833",
  },
  {
    country_name_en: "Israel",
    country_name_fr: "Israël",
    alpha2: "IL",
    alpha3: "ISR",
    number: "376",
  },
  {
    country_name_en: "Italy",
    country_name_fr: "Italie (l')",
    alpha2: "IT",
    alpha3: "ITA",
    number: "380",
  },
  {
    country_name_en: "Jamaica",
    country_name_fr: "Jamaïque (la)",
    alpha2: "JM",
    alpha3: "JAM",
    number: "388",
  },
  {
    country_name_en: "Japan",
    country_name_fr: "Japon (le)",
    alpha2: "JP",
    alpha3: "JPN",
    number: "392",
  },
  {
    country_name_en: "Jersey",
    country_name_fr: "Jersey",
    alpha2: "JE",
    alpha3: "JEY",
    number: "832",
  },
  {
    country_name_en: "Jordan",
    country_name_fr: "Jordanie (la)",
    alpha2: "JO",
    alpha3: "JOR",
    number: "400",
  },
  {
    country_name_en: "Kazakhstan",
    country_name_fr: "Kazakhstan (le)",
    alpha2: "KZ",
    alpha3: "KAZ",
    number: "398",
  },
  {
    country_name_en: "Kenya",
    country_name_fr: "Kenya (le)",
    alpha2: "KE",
    alpha3: "KEN",
    number: "404",
  },
  {
    country_name_en: "Kiribati",
    country_name_fr: "Kiribati",
    alpha2: "KI",
    alpha3: "KIR",
    number: "296",
  },
  {
    country_name_en: "Korea (the Democratic People's Republic of)",
    country_name_fr: "Corée (la République populaire démocratique de)",
    alpha2: "KP",
    alpha3: "PRK",
    number: "408",
  },
  {
    country_name_en: "Korea (the Republic of)",
    country_name_fr: "Corée (la République de)",
    alpha2: "KR",
    alpha3: "KOR",
    number: "410",
  },
  {
    country_name_en: "Kuwait",
    country_name_fr: "Koweït (le)",
    alpha2: "KW",
    alpha3: "KWT",
    number: "414",
  },
  {
    country_name_en: "Kyrgyzstan",
    country_name_fr: "Kirghizistan (le)",
    alpha2: "KG",
    alpha3: "KGZ",
    number: "417",
  },
  {
    country_name_en: "Lao People's Democratic Republic (the)",
    country_name_fr: "Lao (la République démocratique populaire)",
    alpha2: "LA",
    alpha3: "LAO",
    number: "418",
  },
  {
    country_name_en: "Latvia",
    country_name_fr: "Lettonie (la)",
    alpha2: "LV",
    alpha3: "LVA",
    number: "428",
  },
  {
    country_name_en: "Lebanon",
    country_name_fr: "Liban (le)",
    alpha2: "LB",
    alpha3: "LBN",
    number: "422",
  },
  {
    country_name_en: "Lesotho",
    country_name_fr: "Lesotho (le)",
    alpha2: "LS",
    alpha3: "LSO",
    number: "426",
  },
  {
    country_name_en: "Liberia",
    country_name_fr: "Libéria (le)",
    alpha2: "LR",
    alpha3: "LBR",
    number: "430",
  },
  {
    country_name_en: "Libya",
    country_name_fr: "Libye (la)",
    alpha2: "LY",
    alpha3: "LBY",
    number: "434",
  },
  {
    country_name_en: "Liechtenstein",
    country_name_fr: "Liechtenstein (le)",
    alpha2: "LI",
    alpha3: "LIE",
    number: "438",
  },
  {
    country_name_en: "Lithuania",
    country_name_fr: "Lituanie (la)",
    alpha2: "LT",
    alpha3: "LTU",
    number: "440",
  },
  {
    country_name_en: "Luxembourg",
    country_name_fr: "Luxembourg (le)",
    alpha2: "LU",
    alpha3: "LUX",
    number: "442",
  },
  {
    country_name_en: "Macao",
    country_name_fr: "Macao",
    alpha2: "MO",
    alpha3: "MAC",
    number: "446",
  },
  {
    country_name_en: "Madagascar",
    country_name_fr: "Madagascar",
    alpha2: "MG",
    alpha3: "MDG",
    number: "450",
  },
  {
    country_name_en: "Malawi",
    country_name_fr: "Malawi (le)",
    alpha2: "MW",
    alpha3: "MWI",
    number: "454",
  },
  {
    country_name_en: "Malaysia",
    country_name_fr: "Malaisie (la)",
    alpha2: "MY",
    alpha3: "MYS",
    number: "458",
  },
  {
    country_name_en: "Maldives",
    country_name_fr: "Maldives (les)",
    alpha2: "MV",
    alpha3: "MDV",
    number: "462",
  },
  {
    country_name_en: "Mali",
    country_name_fr: "Mali (le)",
    alpha2: "ML",
    alpha3: "MLI",
    number: "466",
  },
  {
    country_name_en: "Malta",
    country_name_fr: "Malte",
    alpha2: "MT",
    alpha3: "MLT",
    number: "470",
  },
  {
    country_name_en: "Marshall Islands (the)",
    country_name_fr: "Marshall (les Îles)",
    alpha2: "MH",
    alpha3: "MHL",
    number: "584",
  },
  {
    country_name_en: "Martinique",
    country_name_fr: "Martinique (la)",
    alpha2: "MQ",
    alpha3: "MTQ",
    number: "474",
  },
  {
    country_name_en: "Mauritania",
    country_name_fr: "Mauritanie (la)",
    alpha2: "MR",
    alpha3: "MRT",
    number: "478",
  },
  {
    country_name_en: "Mauritius",
    country_name_fr: "Maurice",
    alpha2: "MU",
    alpha3: "MUS",
    number: "480",
  },
  {
    country_name_en: "Mayotte",
    country_name_fr: "Mayotte",
    alpha2: "YT",
    alpha3: "MYT",
    number: "175",
  },
  {
    country_name_en: "Mexico",
    country_name_fr: "Mexique (le)",
    alpha2: "MX",
    alpha3: "MEX",
    number: "484",
  },
  {
    country_name_en: "Micronesia (Federated States of)",
    country_name_fr: "Micronésie (États fédérés de)",
    alpha2: "FM",
    alpha3: "FSM",
    number: "583",
  },
  {
    country_name_en: "Moldova (the Republic of)",
    country_name_fr: "Moldova (la République de)",
    alpha2: "MD",
    alpha3: "MDA",
    number: "498",
  },
  {
    country_name_en: "Monaco",
    country_name_fr: "Monaco",
    alpha2: "MC",
    alpha3: "MCO",
    number: "492",
  },
  {
    country_name_en: "Mongolia",
    country_name_fr: "Mongolie (la)",
    alpha2: "MN",
    alpha3: "MNG",
    number: "496",
  },
  {
    country_name_en: "Montenegro",
    country_name_fr: "Monténégro (le)",
    alpha2: "ME",
    alpha3: "MNE",
    number: "499",
  },
  {
    country_name_en: "Montserrat",
    country_name_fr: "Montserrat",
    alpha2: "MS",
    alpha3: "MSR",
    number: "500",
  },
  {
    country_name_en: "Morocco",
    country_name_fr: "Maroc (le)",
    alpha2: "MA",
    alpha3: "MAR",
    number: "504",
  },
  {
    country_name_en: "Mozambique",
    country_name_fr: "Mozambique (le)",
    alpha2: "MZ",
    alpha3: "MOZ",
    number: "508",
  },
  {
    country_name_en: "Myanmar",
    country_name_fr: "Myanmar (le)",
    alpha2: "MM",
    alpha3: "MMR",
    number: "104",
  },
  {
    country_name_en: "Namibia",
    country_name_fr: "Namibie (la)",
    alpha2: "NA",
    alpha3: "NAM",
    number: "516",
  },
  {
    country_name_en: "Nauru",
    country_name_fr: "Nauru",
    alpha2: "NR",
    alpha3: "NRU",
    number: "520",
  },
  {
    country_name_en: "Nepal",
    country_name_fr: "Népal (le)",
    alpha2: "NP",
    alpha3: "NPL",
    number: "524",
  },
  {
    country_name_en: "Netherlands (the)",
    country_name_fr: "Pays-Bas (les)",
    alpha2: "NL",
    alpha3: "NLD",
    number: "528",
  },
  {
    country_name_en: "New Caledonia",
    country_name_fr: "Nouvelle-Calédonie (la)",
    alpha2: "NC",
    alpha3: "NCL",
    number: "540",
  },
  {
    country_name_en: "New Zealand",
    country_name_fr: "Nouvelle-Zélande (la)",
    alpha2: "NZ",
    alpha3: "NZL",
    number: "554",
  },
  {
    country_name_en: "Nicaragua",
    country_name_fr: "Nicaragua (le)",
    alpha2: "NI",
    alpha3: "NIC",
    number: "558",
  },
  {
    country_name_en: "Niger (the)",
    country_name_fr: "Niger (le)",
    alpha2: "NE",
    alpha3: "NER",
    number: "562",
  },
  {
    country_name_en: "Nigeria",
    country_name_fr: "Nigéria (le)",
    alpha2: "NG",
    alpha3: "NGA",
    number: "566",
  },
  {
    country_name_en: "Niue",
    country_name_fr: "Niue",
    alpha2: "NU",
    alpha3: "NIU",
    number: "570",
  },
  {
    country_name_en: "Norfolk Island",
    country_name_fr: "Norfolk (l'Île)",
    alpha2: "NF",
    alpha3: "NFK",
    number: "574",
  },
  {
    country_name_en: "North Macedonia",
    country_name_fr: "Macédoine du Nord (la)",
    alpha2: "MK",
    alpha3: "MKD",
    number: "807",
  },
  {
    country_name_en: "Northern Mariana Islands (the)",
    country_name_fr: "Mariannes du Nord (les Îles)",
    alpha2: "MP",
    alpha3: "MNP",
    number: "580",
  },
  {
    country_name_en: "Norway",
    country_name_fr: "Norvège (la)",
    alpha2: "NO",
    alpha3: "NOR",
    number: "578",
  },
  {
    country_name_en: "Oman",
    country_name_fr: "Oman",
    alpha2: "OM",
    alpha3: "OMN",
    number: "512",
  },
  {
    country_name_en: "Pakistan",
    country_name_fr: "Pakistan (le)",
    alpha2: "PK",
    alpha3: "PAK",
    number: "586",
  },
  {
    country_name_en: "Palau",
    country_name_fr: "Palaos (les)",
    alpha2: "PW",
    alpha3: "PLW",
    number: "585",
  },
  {
    country_name_en: "Palestine, State of",
    country_name_fr: "Palestine, État de",
    alpha2: "PS",
    alpha3: "PSE",
    number: "275",
  },
  {
    country_name_en: "Panama",
    country_name_fr: "Panama (le)",
    alpha2: "PA",
    alpha3: "PAN",
    number: "591",
  },
  {
    country_name_en: "Papua New Guinea",
    country_name_fr: "Papouasie-Nouvelle-Guinée (la)",
    alpha2: "PG",
    alpha3: "PNG",
    number: "598",
  },
  {
    country_name_en: "Paraguay",
    country_name_fr: "Paraguay (le)",
    alpha2: "PY",
    alpha3: "PRY",
    number: "600",
  },
  {
    country_name_en: "Peru",
    country_name_fr: "Pérou (le)",
    alpha2: "PE",
    alpha3: "PER",
    number: "604",
  },
  {
    country_name_en: "Philippines (the)",
    country_name_fr: "Philippines (les)",
    alpha2: "PH",
    alpha3: "PHL",
    number: "608",
  },
  {
    country_name_en: "Pitcairn",
    country_name_fr: "Pitcairn",
    alpha2: "PN",
    alpha3: "PCN",
    number: "612",
  },
  {
    country_name_en: "Poland",
    country_name_fr: "Pologne (la)",
    alpha2: "PL",
    alpha3: "POL",
    number: "616",
  },
  {
    country_name_en: "Portugal",
    country_name_fr: "Portugal (le)",
    alpha2: "PT",
    alpha3: "PRT",
    number: "620",
  },
  {
    country_name_en: "Puerto Rico",
    country_name_fr: "Porto Rico",
    alpha2: "PR",
    alpha3: "PRI",
    number: "630",
  },
  {
    country_name_en: "Qatar",
    country_name_fr: "Qatar (le)",
    alpha2: "QA",
    alpha3: "QAT",
    number: "634",
  },
  {
    country_name_en: "Réunion",
    country_name_fr: "Réunion (La)",
    alpha2: "RE",
    alpha3: "REU",
    number: "638",
  },
  {
    country_name_en: "Romania",
    country_name_fr: "Roumanie (la)",
    alpha2: "RO",
    alpha3: "ROU",
    number: "642",
  },
  {
    country_name_en: "Russian Federation (the)",
    country_name_fr: "Russie (la Fédération de)",
    alpha2: "RU",
    alpha3: "RUS",
    number: "643",
  },
  {
    country_name_en: "Rwanda",
    country_name_fr: "Rwanda (le)",
    alpha2: "RW",
    alpha3: "RWA",
    number: "646",
  },
  {
    country_name_en: "Saint Barthélemy",
    country_name_fr: "Saint-Barthélemy",
    alpha2: "BL",
    alpha3: "BLM",
    number: "652",
  },
  {
    country_name_en: "Saint Helena, Ascension and Tristan da Cunha",
    country_name_fr: "Sainte-Hélène, Ascension et Tristan da Cunha",
    alpha2: "SH",
    alpha3: "SHN",
    number: "654",
  },
  {
    country_name_en: "Saint Kitts and Nevis",
    country_name_fr: "Saint-Kitts-et-Nevis",
    alpha2: "KN",
    alpha3: "KNA",
    number: "659",
  },
  {
    country_name_en: "Saint Lucia",
    country_name_fr: "Sainte-Lucie",
    alpha2: "LC",
    alpha3: "LCA",
    number: "662",
  },
  {
    country_name_en: "Saint Martin (French part)",
    country_name_fr: "Saint-Martin (partie française)",
    alpha2: "MF",
    alpha3: "MAF",
    number: "663",
  },
  {
    country_name_en: "Saint Pierre and Miquelon",
    country_name_fr: "Saint-Pierre-et-Miquelon",
    alpha2: "PM",
    alpha3: "SPM",
    number: "666",
  },
  {
    country_name_en: "Saint Vincent and the Grenadines",
    country_name_fr: "Saint-Vincent-et-les Grenadines",
    alpha2: "VC",
    alpha3: "VCT",
    number: "670",
  },
  {
    country_name_en: "Samoa",
    country_name_fr: "Samoa (le)",
    alpha2: "WS",
    alpha3: "WSM",
    number: "882",
  },
  {
    country_name_en: "San Marino",
    country_name_fr: "Saint-Marin",
    alpha2: "SM",
    alpha3: "SMR",
    number: "674",
  },
  {
    country_name_en: "Sao Tome and Principe",
    country_name_fr: "Sao Tomé-et-Principe",
    alpha2: "ST",
    alpha3: "STP",
    number: "678",
  },
  {
    country_name_en: "Saudi Arabia",
    country_name_fr: "Arabie saoudite (l')",
    alpha2: "SA",
    alpha3: "SAU",
    number: "682",
  },
  {
    country_name_en: "Senegal",
    country_name_fr: "Sénégal (le)",
    alpha2: "SN",
    alpha3: "SEN",
    number: "686",
  },
  {
    country_name_en: "Serbia",
    country_name_fr: "Serbie (la)",
    alpha2: "RS",
    alpha3: "SRB",
    number: "688",
  },
  {
    country_name_en: "Seychelles",
    country_name_fr: "Seychelles (les)",
    alpha2: "SC",
    alpha3: "SYC",
    number: "690",
  },
  {
    country_name_en: "Sierra Leone",
    country_name_fr: "Sierra Leone (la)",
    alpha2: "SL",
    alpha3: "SLE",
    number: "694",
  },
  {
    country_name_en: "Singapore",
    country_name_fr: "Singapour",
    alpha2: "SG",
    alpha3: "SGP",
    number: "702",
  },
  {
    country_name_en: "Sint Maarten (Dutch part)",
    country_name_fr: "Saint-Martin (partie néerlandaise)",
    alpha2: "SX",
    alpha3: "SXM",
    number: "534",
  },
  {
    country_name_en: "Slovakia",
    country_name_fr: "Slovaquie (la)",
    alpha2: "SK",
    alpha3: "SVK",
    number: "703",
  },
  {
    country_name_en: "Slovenia",
    country_name_fr: "Slovénie (la)",
    alpha2: "SI",
    alpha3: "SVN",
    number: "705",
  },
  {
    country_name_en: "Solomon Islands",
    country_name_fr: "Salomon (les Îles)",
    alpha2: "SB",
    alpha3: "SLB",
    number: "090",
  },
  {
    country_name_en: "Somalia",
    country_name_fr: "Somalie (la)",
    alpha2: "SO",
    alpha3: "SOM",
    number: "706",
  },
  {
    country_name_en: "South Africa",
    country_name_fr: "Afrique du Sud (l')",
    alpha2: "ZA",
    alpha3: "ZAF",
    number: "710",
  },
  {
    country_name_en: "South Georgia and the South Sandwich Islands",
    country_name_fr: "Géorgie du Sud-et-les Îles Sandwich du Sud (la)",
    alpha2: "GS",
    alpha3: "SGS",
    number: "239",
  },
  {
    country_name_en: "South Sudan",
    country_name_fr: "Soudan du Sud (le)",
    alpha2: "SS",
    alpha3: "SSD",
    number: "728",
  },
  {
    country_name_en: "Spain",
    country_name_fr: "Espagne (l')",
    alpha2: "ES",
    alpha3: "ESP",
    number: "724",
  },
  {
    country_name_en: "Sri Lanka",
    country_name_fr: "Sri Lanka",
    alpha2: "LK",
    alpha3: "LKA",
    number: "144",
  },
  {
    country_name_en: "Sudan (the)",
    country_name_fr: "Soudan (le)",
    alpha2: "SD",
    alpha3: "SDN",
    number: "729",
  },
  {
    country_name_en: "Suriname",
    country_name_fr: "Suriname (le)",
    alpha2: "SR",
    alpha3: "SUR",
    number: "740",
  },
  {
    country_name_en: "Svalbard and Jan Mayen",
    country_name_fr: "Svalbard et l'Île Jan Mayen (le)",
    alpha2: "SJ",
    alpha3: "SJM",
    number: "744",
  },
  {
    country_name_en: "Sweden",
    country_name_fr: "Suède (la)",
    alpha2: "SE",
    alpha3: "SWE",
    number: "752",
  },
  {
    country_name_en: "Switzerland",
    country_name_fr: "Suisse (la)",
    alpha2: "CH",
    alpha3: "CHE",
    number: "756",
  },
  {
    country_name_en: "Syrian Arab Republic (the)",
    country_name_fr: "République arabe syrienne (la)",
    alpha2: "SY",
    alpha3: "SYR",
    number: "760",
  },
  {
    country_name_en: "Taiwan (Province of China)",
    country_name_fr: "Taïwan (Province de Chine)",
    alpha2: "TW",
    alpha3: "TWN",
    number: "158",
  },
  {
    country_name_en: "Tajikistan",
    country_name_fr: "Tadjikistan (le)",
    alpha2: "TJ",
    alpha3: "TJK",
    number: "762",
  },
  {
    country_name_en: "Tanzania, the United Republic of",
    country_name_fr: "Tanzanie (la République-Unie de)",
    alpha2: "TZ",
    alpha3: "TZA",
    number: "834",
  },
  {
    country_name_en: "Thailand",
    country_name_fr: "Thaïlande (la)",
    alpha2: "TH",
    alpha3: "THA",
    number: "764",
  },
  {
    country_name_en: "Timor-Leste",
    country_name_fr: "Timor-Leste (le)",
    alpha2: "TL",
    alpha3: "TLS",
    number: "626",
  },
  {
    country_name_en: "Togo",
    country_name_fr: "Togo (le)",
    alpha2: "TG",
    alpha3: "TGO",
    number: "768",
  },
  {
    country_name_en: "Tokelau",
    country_name_fr: "Tokelau (les)",
    alpha2: "TK",
    alpha3: "TKL",
    number: "772",
  },
  {
    country_name_en: "Tonga",
    country_name_fr: "Tonga (les)",
    alpha2: "TO",
    alpha3: "TON",
    number: "776",
  },
  {
    country_name_en: "Trinidad and Tobago",
    country_name_fr: "Trinité-et-Tobago (la)",
    alpha2: "TT",
    alpha3: "TTO",
    number: "780",
  },
  {
    country_name_en: "Tunisia",
    country_name_fr: "Tunisie (la)",
    alpha2: "TN",
    alpha3: "TUN",
    number: "788",
  },
  {
    country_name_en: "Turkey",
    country_name_fr: "Turquie (la)",
    alpha2: "TR",
    alpha3: "TUR",
    number: "792",
  },
  {
    country_name_en: "Turkmenistan",
    country_name_fr: "Turkménistan (le)",
    alpha2: "TM",
    alpha3: "TKM",
    number: "795",
  },
  {
    country_name_en: "Turks and Caicos Islands (the)",
    country_name_fr: "Turks-et-Caïcos (les Îles)",
    alpha2: "TC",
    alpha3: "TCA",
    number: "796",
  },
  {
    country_name_en: "Tuvalu",
    country_name_fr: "Tuvalu (les)",
    alpha2: "TV",
    alpha3: "TUV",
    number: "798",
  },
  {
    country_name_en: "Uganda",
    country_name_fr: "Ouganda (l')",
    alpha2: "UG",
    alpha3: "UGA",
    number: "800",
  },
  {
    country_name_en: "Ukraine",
    country_name_fr: "Ukraine (l')",
    alpha2: "UA",
    alpha3: "UKR",
    number: "804",
  },
  {
    country_name_en: "United Arab Emirates (the)",
    country_name_fr: "Émirats arabes unis (les)",
    alpha2: "AE",
    alpha3: "ARE",
    number: "784",
  },
  {
    country_name_en:
      "United Kingdom of Great Britain and Northern Ireland (the)",
    country_name_fr: "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord (le)",
    alpha2: "GB",
    alpha3: "GBR",
    number: "826",
  },
  {
    country_name_en: "United States Minor Outlying Islands (the)",
    country_name_fr: "Îles mineures éloignées des États-Unis (les)",
    alpha2: "UM",
    alpha3: "UMI",
    number: "581",
  },
  {
    country_name_en: "United States of America (the)",
    country_name_fr: "États-Unis d'Amérique (les)",
    alpha2: "US",
    alpha3: "USA",
    number: "840",
  },
  {
    country_name_en: "Uruguay",
    country_name_fr: "Uruguay (l')",
    alpha2: "UY",
    alpha3: "URY",
    number: "858",
  },
  {
    country_name_en: "Uzbekistan",
    country_name_fr: "Ouzbékistan (l')",
    alpha2: "UZ",
    alpha3: "UZB",
    number: "860",
  },
  {
    country_name_en: "Vanuatu",
    country_name_fr: "Vanuatu (le)",
    alpha2: "VU",
    alpha3: "VUT",
    number: "548",
  },
  {
    country_name_en: "Venezuela (Bolivarian Republic of)",
    country_name_fr: "Venezuela (République bolivarienne du)",
    alpha2: "VE",
    alpha3: "VEN",
    number: "862",
  },
  {
    country_name_en: "Viet Nam",
    country_name_fr: "Viet Nam (le)",
    alpha2: "VN",
    alpha3: "VNM",
    number: "704",
  },
  {
    country_name_en: "Virgin Islands (British)",
    country_name_fr: "Vierges britanniques (les Îles)",
    alpha2: "VG",
    alpha3: "VGB",
    number: "092",
  },
  {
    country_name_en: "Virgin Islands (U.S.)",
    country_name_fr: "Vierges des États-Unis (les Îles)",
    alpha2: "VI",
    alpha3: "VIR",
    number: "850",
  },
  {
    country_name_en: "Wallis and Futuna",
    country_name_fr: "Wallis-et-Futuna",
    alpha2: "WF",
    alpha3: "WLF",
    number: "876",
  },
  {
    country_name_en: "Western Sahara*",
    country_name_fr: "Sahara occidental (le)*",
    alpha2: "EH",
    alpha3: "ESH",
    number: "732",
  },
  {
    country_name_en: "Yemen",
    country_name_fr: "Yémen (le)",
    alpha2: "YE",
    alpha3: "YEM",
    number: "887",
  },
  {
    country_name_en: "Zambia",
    country_name_fr: "Zambie (la)",
    alpha2: "ZM",
    alpha3: "ZMB",
    number: "894",
  },
  {
    country_name_en: "Zimbabwe",
    country_name_fr: "Zimbabwe (le)",
    alpha2: "ZW",
    alpha3: "ZWE",
    number: "716",
  },
];

const getCountryCode = (alpha2) => {
  //@Todo this could be optimized in future
  //currently looping through all
  let result = null;
  for (let item of db) {
    if (item.alpha2 === alpha2) {
      return item.alpha3;
    }
  }
};

export default getCountryCode;
